# Site settings
title: OpenPGP Public Keyserver
email: matt@mattrude.com
description: ""
url: "http://devel-keyserver.mattrude.com"
baseurl: "devel-keyserver.mattrude.com"
destination: "/var/www/devel"

# Bootstrap
bootstrap_version: 3.3.1

# Analytics settings
google_analytics_id: UA-55622044-1

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

exclude:
- README.md
- css/syntax.less

gems:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-last-modified-at
#- jekyll-less
#- jekyll-press


jekyll-press:
  exclude: 'robots.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
